name: native_updater
description: Flutter package for prompting users to upgrade with native dialog when there is a newer version of the app in the store.
version: 0.0.1
author: Jeffry Hermanto <jeffryhermanto@loadsmile.com>
homepage: https://github.com/loadsmileau/native_updater

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
