name: native_updater
description: Flutter package for prompting users to upgrade with native dialog when there is a newer version of the app in the store.
version: 0.0.1
author: Jeffry Hermanto <jeffryhermanto@loadsmile.com>
homepage: https://github.com/loadsmileau/native_updater

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # package_info will help us to find current installed version of application.
  package_info: ^0.4.0+16
  # url_launcher will help us to trigger app store / play store url from our app.
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
